[versions]
checkstyle = "13.3.0"
spring-modulith = "2.1.0"
platform-integration-starter = "1.0.6"

[libraries]
platform-integration-spring-boot-starter = { module = "app.runlume.platform:platform-integration-spring-boot-starter", version.ref = "platform-integration-starter" }
spring-modulith-bom = { module = "org.springframework.modulith:spring-modulith-bom", version.ref = "spring-modulith" }
spring-modulith-api = { module = "org.springframework.modulith:spring-modulith-api" }
spring-modulith-starter-test = { module = "org.springframework.modulith:spring-modulith-starter-test" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
testcontainers-junit = { module = "org.testcontainers:testcontainers-junit-jupiter" }
